/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nextstep.jwp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JwpApplicationTest {
    @Test void appHasAGreeting() {
        JwpApplication classUnderTest = new JwpApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
